# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_remove_dataset_elements'),
        ('users', '0001_initial')
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='technicaluser',
            name='user',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.TechnicalUser'),
        ),
        migrations.DeleteModel(
            name='EndUser',
        ),
        migrations.DeleteModel(
            name='TechnicalUser',
        ),
    ]
