# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('label', '0003_auto_20170712_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dataelement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.DataElement')),
            ],
        ),
        migrations.CreateModel(
            name='LabelChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parentset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='labelchoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.LabelChoice'),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.EndUser'),
        ),
    ]
