# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0007_auto_20170714_1211')
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='parentset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.Dataset'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TechnicalUser'),
        ),
        migrations.AlterField(
            model_name='label',
            name='dataelement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.DataElement'),
        ),
    ]
