# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_auto_20170714_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='parentset',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='labelchoice',
            name='parentset',
        ),
        migrations.AlterField(
            model_name='label',
            name='dataelement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.DataElement'),
        ),
        migrations.AlterField(
            model_name='label',
            name='labelchoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.LabelChoice'),
        ),
        migrations.DeleteModel(
            name='Dataelement',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='LabelChoice',
        ),
    ]
